### ISSUE TITLE
Unable to install addon

### ISSUE THREAD

**Issue by jkerman2000** [DarklightGames/io_scene_psk_psa#90]
**Versions**
Blender: 4.0.2
io_scene_psk_psa: 7.0.0

**Describe the bug**
The addon "installs," but when clicking the activation box it gives the following error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_psk_psa\__init__.py", line 61, in <module>
    from .psk.import_ import operators as psk_import_operators
  File "C:\Program Files\Pixar\RenderManProServer-25.2\lib\python3.10\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\io_scene_psk_psa\psk\import_\operators.py", line 5, in <module>
    from bpy.types import Operator, FileHandler, Context
ImportError: cannot import name 'FileHandler' from 'bpy.types' (unknown location)

**Comment by jkerman2000** [comment]
Note: no idea why my Renderman install is part of the error. I removed the Renderman addon, and it still threw the error at me.

**Comment by jkerman2000** [comment]
Never mind, I'm just a big doofus. I should have installed version 6 to blender 4.0
